CREATE OR ALTER VIEW VW_FIS_CourseHours
AS
	SELECT
		AcademicYear = RIGHT ( CAST ( YEAR ( FY.START_DATE ) AS VARCHAR(4) ), 2 ) + '/' + RIGHT ( CAST ( YEAR ( FY.END_DATE ) AS VARCHAR(4) ), 2 ),
		ProvSpecValue = UIO.FES_UINS_INSTANCE_CODE,
		PlannedHours = COALESCE ( UQA.GUIDED_HOURS, 0 ),
		EEPHours = COALESCE ( UQA.PLANNED_EEP_HOURS, 0 ),
		TLevelHours = COALESCE ( UQA.PLANNED_HOURS, 0 )
	FROM [EBS-DB\EBS].ebs.dbo.UNIT_INSTANCE_OCCURRENCES UIO
	INNER JOIN [EBS-DB\EBS].ebs.dbo.UNIT_INSTANCES UI
		ON UI.FES_UNIT_INSTANCE_CODE = UIO.FES_UINS_INSTANCE_CODE
	INNER JOIN [EBS-DB\EBS].ebs.dbo.FUNDING_YEARS FY
		ON FY.FUNDING_YEAR = '32'
	INNER JOIN [EBS-DB\EBS].ebs.dbo.ORGANISATION_UNITS FAC
		ON FAC.ORGANISATION_CODE = UIO.OWNING_ORGANISATION
	INNER JOIN [EBS-DB\EBS].ebs.dbo.ORGANISATION_UNITS TEAM
		ON TEAM.ORGANISATION_CODE = UIO.OFFERING_ORGANISATION
	LEFT JOIN (
		-- In case of duplicates
		SELECT
			AimID = UQA.ID,
			AimFundingYear = UQA.FUNDING_YEAR,
			AimCourseID = UQA.UIO_ID,
			AimIsDefault = UQA.DEFAULT_QA,
			RowNum = 
				ROW_NUMBER () OVER (
					PARTITION BY
						UQA.FUNDING_YEAR,
						UQA.UIO_ID
					ORDER BY
						UQA.DEFAULT_QA DESC
				)
		FROM [EBS-DB\EBS].ebs.dbo.UIO_QUAL_AIMS UQA
		WHERE UQA.FUNDING_YEAR = '32'
	) UQAM
		ON UQAM.AimCourseID = UIO.UIO_ID
		AND UQAM.AimFundingYear = FY.FUNDING_YEAR
		AND UQAM.RowNum = 1
	LEFT JOIN [EBS-DB\EBS].ebs.dbo.UIO_QUAL_AIMS UQA
		ON UQA.ID = UQAM.AimID
	WHERE
		--UIO.CALOCC_OCCURRENCE_CODE = REPLACE ( @AcademicYear, '/', '' )
		COALESCE ( UQA.START_DATE, UIO.FES_START_DATE ) <= FY.END_DATE
		AND COALESCE ( UQA.END_DATE, UIO.FES_END_DATE ) >= FY.START_DATE