CREATE VIEW VW_FIS_Disabilities
AS
	SELECT
		Code = DIS.LOW_VALUE,
		Description = DIS.FES_LONG_DESCRIPTION
	FROM [EBS-DB\EBS].ebs.dbo.VERIFIERS DIS
	WHERE
		DIS.RV_DOMAIN = 'DISABILITY_TYPE'
		AND DIS.FES_ACTIVE = 'Y'